/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bdzvdctwlicfzglpgboh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkenZkY3R3bGljZnpnbHBnYm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NDU1MzIsImV4cCI6MjA5MjUyMTUzMn0.9W-7kBUF-X-U4dMX4yF-ZGf5aMkQFhVCOFYcseQDV84"